import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar";
import Aos from "./_Components/Aos";
import ScrollToTop from "./_Components/ScrollToTop";

import "@fortawesome/fontawesome-free/css/all.min.css";
import { Toaster } from "react-hot-toast";
import MySessionProvider from "@/MySessionProvider/MySessionProvider";
import CartProvider from "./context/CartCountContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                
        <ScrollToTop/>
        <MySessionProvider>
          <CartProvider>
            <Toaster />
            <Aos />

            <div>
              <Navbar />
            </div>
            <div className="mt-20"></div>
            {children}
          </CartProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
